### ISSUE TITLE
Java 11 not supported

### ISSUE THREAD

**Issue by fjjimenezv** [adobe/aem-spa-project-archetype#60]
The documentation talks about "Java 1.8 or higher", but I cannot compile with Java 11.0.2.
Changing to Java 1.8.121 it works 

This is the detail of the error

[INFO] [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.989 s <<< FAILURE! - in com.adobe.spa.test.projects.internal.models.PageImplTest
[INFO] [ERROR] testConfigChildPage(com.adobe.spa.test.projects.internal.models.PageImplTest)  Time elapsed: 0.152 s  <<< ERROR!
[INFO] java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
[INFO] 	at com.adobe.spa.test.projects.internal.models.PageImplTest.testConfigChildPage(PageImplTest.java:213)
[INFO] Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
[INFO] 	at com.adobe.spa.test.projects.internal.models.PageImplTest.testConfigChildPage(PageImplTest.java:213)
[INFO] 
[INFO] [ERROR] testRequestFilteredNestedChildPages(com.adobe.spa.test.projects.internal.models.PageImplTest)  Time elapsed: 0.012 s  <<< ERROR!
[INFO] java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
[INFO] 	at com.adobe.spa.test.projects.internal.models.PageImplTest.testRequestFilteredNestedChildPages(PageImplTest.java:235)
[INFO] 
[INFO] [INFO] 
[INFO] [INFO] Results:
[INFO] [INFO] 
[INFO] [ERROR] Errors: 
[INFO] [ERROR]   PageImplTest.testConfigChildPage:213 » NoClassDefFound javax/annotation/PostCo...
[INFO] [ERROR]   PageImplTest.testRequestFilteredNestedChildPages:235 » NoClassDefFound javax/a...
[INFO] [INFO] 
[INFO] [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
[INFO] [INFO] 
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Reactor Summary:
[INFO] [INFO] 
[INFO] [INFO] Test SPA Angular Project Reactor ................... SUCCESS [  0.403 s]
[INFO] [INFO] Test SPA Angular Project Core ...................... FAILURE [ 32.001 s]

**Comment by lydiapuric** [comment]
Thanks for filing the issue.
We will check and come back with the result.

**Comment by pfauchere** [comment]
issue tracked internally by CQ-4266181

**Comment by pfauchere** [comment]
A similar work has been performed on the _We.Retail Journal_ sample project.

See https://github.com/adobe/aem-sample-we-retail-journal/commit/6af61df13035a95fa14af79c6d5c3178ed702e10
