### PR TITLE
Add support for Java 11

### LINKED ISSUE #60: Java 11 not supported
The documentation talks about "Java 1.8 or higher", but I cannot compile with Java 11.0.2.
Changing to Java 1.8.121 it works 

This is the detail of the error

[INFO] [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.989 s <<< FAILURE! - in com.adobe.spa.test.projects.internal.models.PageImplTest
[INFO] [ERROR] testConfigChildPage(com.adobe.spa.test.projects.internal.models.PageImplTest)  Time elapsed: 0.152 s  <<< ERROR!
[INFO] java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
[INFO] 	at com.adobe.spa.test.projects.internal.models.PageImplTest.testConfigChildPage(PageImplTest.java:213)
[INFO] Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
[INFO] 	at com.adobe.spa.test.projects.internal.models.PageImplTest.testConfigChildPage(PageImplTest.java:213)
[INFO] 
[INFO] [ERROR] testRequestFilteredNestedChildPages(com.adobe.spa.test.projects.internal.models.PageImplTest)  Time elapsed: 0.012 s  <<< ERROR!
[INFO] java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
[INFO] 	at com.adobe.spa.test.projects.internal.models.PageImplTest.testRequestFilteredNestedChildPages(PageImplTest.java:235)
[INFO] 
[INFO] [INFO] 
[INFO] [INFO] Results:
[INFO] [INFO] 
[INFO] [ERROR] Errors: 
[INFO] [ERROR]   PageImplTest.testConfigChildPage:213 » NoClassDefFound javax/annotation/PostCo...
[INFO] [ERROR]   PageImplTest.testRequestFilteredNestedChildPages:235 » NoClassDefFound javax/a...
[INFO] [INFO] 
[INFO] [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
[INFO] [INFO] 
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Reactor Summary:
[INFO] [INFO] 
[INFO] [INFO] Test SPA Angular Project Reactor ................... SUCCESS [  0.403 s]
[INFO] [INFO] Test SPA Angular Project Core ...................... FAILURE [ 32.001 s]

### PR DESCRIPTION
**Pull request by samuelmeuli**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #60
| Patch: Bug Fix?          | No
| Minor: New Feature?      | No
| Major: Breaking Change?  | Yes
| Tests Added + Pass?      | No
| Documentation Provided   | No
| Any Dependency Changes?  | Yes
| License                  | Apache License, Version 2.0

This PR fixes the project's compatibility with Java 11. The changes made are the same as in the PRs https://github.com/adobe/aem-sample-we-retail-journal/pull/45 and https://github.com/adobe/aem-core-wcm-components/pull/500. They are discussed in https://github.com/adobe/aem-core-wcm-components/issues/491.

### CODE REVIEW

File: src/main/resources/archetype-resources/core/src/main/java/internal/models/HierarchyPageImpl.java [hunk 1]
```diff
@@ -23,8 +23,8 @@
 import java.util.Map;
 import java.util.regex.Pattern;
 
-import javax.annotation.Nonnull;
-import javax.annotation.Nullable;
+import org.jetbrains.annotations.NotNull;
```
Comment (habansal) [inline src/main/resources/archetype-resources/core/src/main/java/internal/models/HierarchyPageImpl.java]: [Minor] - Import statement order needs to be fixed.
Ideally, the order of package imports is -

java.*
_blank line_
javax.*
_blank line_
org.*
_blank line_
*
_blank line_
import static *

**Comment by samuelmeuli** [comment]
Fixed the import order and rebased on `development`.
